import type { Metadata } from "next";
import Link from "next/link";
import { ArticleCta, SiteFooter, SiteHeader } from "../../site-chrome";

export const metadata: Metadata = { title: "Why Won’t My Slush Freeze?", description: "Learn the most common reasons a home slush-machine mixture stays liquid, freezes too hard, or turns icy—and what to check next.", alternates: { canonical: "https://www.slushiq.com/learn/fix-my-slush" } };

export default function FixMySlushPage() {
  return <><SiteHeader /><main className="article-page"><header className="article-hero"><p className="section-kicker">SLUSH TROUBLESHOOTING</p><h1>Why won’t my<br /><em>slush freeze?</em></h1><p>A frozen-drink machine needs enough dissolved sugar to keep a mixture smooth—but not so much sugar or alcohol that the mixture stays liquid. The exact balance depends on the full batch, not one ingredient in isolation.</p></header><div className="article-body"><article><p className="article-lede">Most freezing problems are not machine failures. They come from the balance of sugar, alcohol, water, and temperature inside the bowl.</p><h2>Start with these four checks</h2><section><span>01</span><div><h3>Give the machine enough time</h3><p>Begin with a thoroughly chilled mixture and follow your machine’s operating instructions. A warm batch can look like a formula problem while the machine is still removing heat.</p></div></section><section><span>02</span><div><h3>Check total alcohol</h3><p>Alcohol resists freezing. More spirits, liqueurs, or wine can push a batch outside the machine’s usable range even when the drink tastes balanced.</p></div></section><section><span>03</span><div><h3>Check the full sugar load</h3><p>Sugar comes from more than simple syrup. Juice, soda, liqueurs, purées, and bottled mixers all contribute to the batch.</p></div></section><section><span>04</span><div><h3>Measure before adding more</h3><p>Random additions can make the problem harder to diagnose. Record what is already in the bowl, including brands and amounts, before making an adjustment.</p></div></section><div className="callout"><b>Important:</b><p>Do not use a single universal Brix target as a guarantee. Alcohol changes the relationship between a refractometer reading and actual sugar concentration. SlushIQ evaluates the ingredient composition of the full batch.</p></div><h2>What if it freezes too hard?</h2><p>A mixture that becomes overly firm or icy may not contain enough dissolved solids for the texture you want. Avoid repeatedly restarting the machine or adding ingredients blindly. Capture the complete recipe first, then make one measured adjustment.</p><h2>What SlushIQ adds</h2><p>Brixley and SlushIQ’s labs turn your ingredient list into a batch-level analysis. You get an understandable recommendation instead of working backward from a generic ratio.</p><div className="next-reading"><span>KEEP LEARNING</span><Link href="/learn/what-is-brix">What Brix means for frozen drinks →</Link><Link href="/learn/alcohol-and-slush">How alcohol changes the freeze →</Link></div></article><ArticleCta /></div></main><SiteFooter /></>;
}
