import type { Metadata } from "next";
import { MobileMenu } from "./mobile-menu";
import { ReturnLink } from "./return-link";
import { DownloadCta } from "./site-chrome";
import { AppScreenshot, BrixleyImage } from "./marketing-image";

export const metadata: Metadata = {
  title: { absolute: "SlushIQ | Slush Machine Calculator & Frozen Drink App" },
  description:
    "Use SlushIQ to calculate sugar, alcohol, and dilution for Ninja SLUSHi, Iceman, and other home slush machines. Build, scale, save, and fix frozen drinks.",
  alternates: { canonical: "https://slushiq.com/" },
};

const appStore = "https://apps.apple.com/us/app/slushiq/id6749187530";
const playStore = "https://play.google.com/store/apps/details?id=com.slushiq.app";

const faqs = [
  ["What should I check if my slush stays liquid?", "Sugar and alcohol both lower a mixture’s freezing point. SlushIQ reads the whole batch and shows what to adjust before more time and ingredients are wasted."],
  ["Does SlushIQ work with my machine?", "SlushIQ is designed for home frozen-drink machines, including the Ninja SLUSHi Professional (often called the Ninja SLUSHi Pro), Ninja SLUSHi XL, Ninja SLUSHi Max, Ninja SLUSHi Twist, Iceman Slush-Ease, VEVOR no-ice slushie machines, and GreenPan Frost frozen drink makers. SlushIQ helps calculate the complete mixture, but always follow the capacity, ingredient, and operating guidance for your exact machine. SlushIQ is an independent product and is not affiliated with or endorsed by Ninja, Iceman, VEVOR, or GreenPan."],
  ["Do I need to understand Brix?", "No. SlushIQ handles the calculations and translates the result into plain-language guidance. You can learn the science—or simply follow the adjustment."],
  ["Are SlushIQ recipes AI-generated?", "No. Recipes in the SlushIQ collection are designed by people with home frozen-drink machines in mind. They are not generated by AI."],
  ["Why aren’t recipes published on this website?", "SlushIQ recipes stay inside the app because they are more useful there than on a static webpage. In the app, you can scale a recipe for your batch size, save favorites to My Library, keep custom recipes, and use the SlushIQ tools when a mixture needs adjusting. The website focuses on frozen-drink guidance and slush science, while the complete interactive recipe experience lives in the iPhone and Android app."],
];

const reviews = [
  { name: "Alice H.", date: "May 2, 2026", quote: "Love this app, really easy to use and find recipes. Love how it gets measurements for recipes to fix your own tried ones." },
  { name: "Pepper B.", date: "July 9, 2026", quote: "SlushIQ is worth every penny. The app is easy to use, reliable, and works exactly as advertised. What impressed me most was the outstanding customer support—fast, friendly, and genuinely helpful." },
  { name: "Andrew K.", date: "January 21, 2026", quote: "Easy to use, takes a lot of guesswork out of making sure my mix will slush. I’m using the Iceman Slush Ease and the calculator in here has never failed me." },
  { name: "Sarah L.", date: "June 5, 2026", quote: "Very handy app!" },
  { name: "Damien", date: "January 11, 2026", quote: "Great app. I love the features and the way everything is set up. User friendly and great color scheme." },
  { name: "Marson G.", date: "December 26, 2025", quote: "Slushies, here I come! I got a slushy machine for Christmas and this app is awesome. Takes out all the guesswork." },
  { name: "Brandi M.", date: "December 23, 2025", quote: "This app is excellent. It takes the guesswork out of making a slushie. Michael is very helpful." },
];

function Wordmark() {
  return <span className="wordmark"><BrixleyImage alt="" sizes="46px" priority />Slush<span>IQ</span></span>;
}

function StoreButtons({ compact = false }: { compact?: boolean }) {
  return (
    <div className={`store-buttons ${compact ? "compact" : ""}`}>
      <a href={appStore} target="_blank" rel="noreferrer" aria-label="Download SlushIQ on the App Store" data-analytics-event="app_store_click" data-analytics-placement="store_buttons">
        <img src="/app-store-badge.svg" width="120" height="40" alt="Download on the App Store" />
      </a>
      <a href={playStore} target="_blank" rel="noreferrer" aria-label="Get SlushIQ on Google Play" data-analytics-event="google_play_click" data-analytics-placement="store_buttons">
        <img src="/google-play-badge.png" width="478" height="142" alt="Get it on Google Play" />
      </a>
    </div>
  );
}

function PhoneMockup() {
  return (
    <div className="phone-wrap" aria-label="Preview of the SlushIQ app">
      <div className="orbit orbit-one" />
      <div className="orbit orbit-two" />
      <div className="phone">
        <AppScreenshot className="real-app-screen" src="/app-home.png" alt="SlushIQ app home screen" sizes="(max-width: 650px) 250px, 290px" priority />
      </div>
    </div>
  );
}

export default function Home() {
  const schema = { "@context": "https://schema.org", "@graph": [
    { "@type": "SoftwareApplication", name: "SlushIQ", applicationCategory: "FoodApplication", operatingSystem: "iOS, Android", description: "A slush machine calculator and frozen drink troubleshooting app for home machines.", url: "https://slushiq.com/", downloadUrl: [appStore, playStore], offers: { "@type": "Offer", availability: "https://schema.org/InStock" } },
    { "@type": "WebSite", name: "SlushIQ", url: "https://slushiq.com/" },
    { "@type": "FAQPage", mainEntity: faqs.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) }
  ] };

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
      <header className="site-header">
        <nav className="header-nav header-nav-primary" aria-label="Download SlushIQ">
          <a className="header-download ios" href={appStore} target="_blank" rel="noreferrer">Download on iOS</a>
          <a className="header-download android" href={playStore} target="_blank" rel="noreferrer">Download on Android</a>
        </nav>
        <a href="#top" className="logo-link header-brand" aria-label="SlushIQ home"><Wordmark /></a>
        <div className="header-nav header-nav-secondary">
          <a href="#top">Home</a><a href="#features">Tools</a><a href="/labs">How it works</a><a href="/learn">Learn</a><a href="#faq">FAQ</a>
        </div>
        <MobileMenu />
      </header>

      <main id="top">
        <section className="hero">
          <div className="hero-glow" />
          <div className="hero-copy">
            <h1>Better slush.<br /><em>Zero guesswork.</em></h1>
            <p>A slush machine calculator with human-created frozen drink recipes for Ninja SLUSHi, Iceman, and other home slushie machines. SlushIQ helps balance sugar, alcohol, and dilution so every batch comes out smooth and ready to pour.</p>
            <div className="hero-download-block"><div className="no-sub-badge"><div><b>No subscription fees.</b><small>Just download, mix, and slush.</small></div></div><StoreButtons /></div>
            <div className="proof platform-proof"><div><b>3K+</b><span>Downloads*</span></div><div><b>5.0</b><span>Apple rating</span></div><div><b>4.8</b><span>Google Play</span></div><div><b>#3</b><span>Food &amp; Drink*</span></div></div>
          </div>
          <PhoneMockup />
          <BrixleyImage className="hero-brixley" alt="Brixley, the SlushIQ frozen drink assistant" sizes="(max-width: 650px) 100px, 185px" priority />
          <p className="scroll-note">SCROLL TO DISCOVER <span>↓</span></p>
        </section>

        <div className="batch-story" id="how">
          <section className="story-phase choose-phase" id="features">
            <div className="tool-tour" aria-label="SlushIQ tools">
              <article className="tool-stop recipes-library"><div className="tool-copy"><span className="tool-index">SLUSHIQ TOOLS / BROWSE + SAVE</span><h3>Frozen drink recipes.<br /><em>Your own library.</em></h3><div className="recipe-trust"><span>✓</span><div><b>Designed by people. Not generated by AI.</b><small>SlushIQ recipes are created with home frozen-drink machines in mind.</small></div></div><div className="tool-breakdown"><p><b>Recipes</b><small>Need a place to start?</small> Browse human-created frozen drink recipes developed for Ninja SLUSHi, Iceman, and other home slushie machines. The full recipe collection stays inside the SlushIQ app.</p><p><b>My Library</b><small>Want to save what works?</small> Keep favorite recipes and custom slush recipes together, then reopen and scale a successful batch whenever you make it again.</p></div><a className="tool-learn-link" href="/recipes-and-library">Explore Recipes &amp; My Library →</a></div><div className="tool-screens dual"><AppScreenshot src="/app-recipes.png" alt="Frozen drink recipes in the SlushIQ recipe app" /><AppScreenshot src="/app-library.png" alt="Saved and custom slush recipes in My Library" /></div></article>
              <article className="tool-stop labs-brixley"><div className="tool-copy"><span>SLUSHIQ TOOLS / BUILD + FIX</span><h3>Three ways to get<br /><em>the balance right.</em></h3><div className="tool-breakdown"><p><b>SimpleLAB</b><small>Have a store-bought mixer?</small> Enter the serving size and sugar from the mixer’s nutrition label, choose an alcoholic or non-alcoholic batch, and SimpleLAB calculates the mixer, water, and liquor—when needed. Alcoholic batches target 11.8 Brix and 8–9% final-batch ABV.</p><p><b>DesignLAB</b><small>Creating something new?</small> Build ingredient by ingredient while SlushIQ tracks sugar, alcohol, dilution, and total volume. Choose the freeze behavior you want—or use Auto-Balance when you want help bringing the mix into a workable range. Flavor in. Freeze balance out.</p><p><b>Brixley</b><small>Need to get a batch back on track?</small> Use the power of AI to walk through what went into the bowl. Brixley reviews the complete mix, applies SlushIQ’s freeze math, and recommends a practical adjustment you can measure and pour.</p></div><a className="tool-learn-link" href="/labs">Explore the SlushIQ Labs →</a></div><div className="tool-screens trio"><figure><AppScreenshot src="/app-simplelab.png" alt="SimpleLAB batch calculator in SlushIQ" /></figure><figure><AppScreenshot src="/app-designlab.png" alt="DesignLAB recipe builder with Auto-Balance and adjustable freeze behavior" /></figure><figure><AppScreenshot src="/app-brixley.png" alt="Brixley AI frozen drink assistant for troubleshooting a slush batch" /></figure></div></article>
            </div>
          </section>

        </div>

        <section className="reviews" aria-labelledby="reviews-title">
          <div className="reviews-heading"><p className="section-kicker">FROM REAL SLUSHIQ USERS</p><h2 id="reviews-title">Built in the app.<br /><em>Proven at the machine.</em></h2><div className="reviews-summary"><p>More than 3,000 downloads and counting. Home slush-machine owners are using SlushIQ to build, repair, and repeat batches with confidence.</p><div className="review-stats"><div><b>3K+</b><span>Downloads</span></div><div><b>5.0</b><span>Apple rating</span></div><div><b>4.8</b><span>Google Play rating</span></div><div><b>#3</b><span>Apple Food &amp; Drink*</span></div></div><small>*Downloads, Apple App Store position, and platform ratings as reported July 20, 2026. Rankings and ratings change over time.</small></div></div>
          <div className="review-marquee">
            <div className="review-track">
              {reviews.map((review) => <blockquote className="review-card" key={review.name}><header className="review-card-head"><div><b>{review.name}</b><time>{review.date}</time></div><span aria-label="5 out of 5 stars">★★★★★</span></header><p><i>“</i>{review.quote}<i>”</i></p></blockquote>)}
              {reviews.map((review) => <blockquote className="review-card" aria-hidden="true" key={`repeat-${review.name}`}><header className="review-card-head"><div><b>{review.name}</b><time>{review.date}</time></div><span>★★★★★</span></header><p><i>“</i>{review.quote}<i>”</i></p></blockquote>)}
            </div>
          </div>
        </section>

        <section className="learn" id="learn">
          <div className="learn-copy"><p className="section-kicker">LEARN THE “WHY”</p><h2>Slush science<br /><em>in plain English.</em></h2><p>Helpful guides answer the questions people ask before and after they fill the machine. No full recipes required.</p><a className="section-text-link" href="/learn">Browse all SlushIQ guides <span>→</span></a></div>
          <div className="article-list">
            <ReturnLink href="/learn/fix-my-slush" returnHash="#learn"><span>01</span><div><small>TROUBLESHOOTING</small><b>Why won’t my slush freeze?</b></div><i>→</i></ReturnLink>
            <ReturnLink href="/learn/what-is-brix" returnHash="#learn"><span>02</span><div><small>SLUSH BASICS</small><b>What Brix means for frozen drinks</b></div><i>→</i></ReturnLink>
            <ReturnLink href="/learn/sugar-free-ninja-slushi" returnHash="#learn"><span>03</span><div><small>SUGAR-FREE SLUSH</small><b>Why diet drinks need a different freeze plan</b></div><i>→</i></ReturnLink>
          </div>
        </section>

        <section className="faq" id="faq"><p className="section-kicker">QUICK ANSWERS</p><div className="faq-layout"><div className="faq-intro"><h2>Frequently Asked<br /><em>questions.</em></h2><p>Home slush machines look simple, but the mixture inside them is doing several things at once. Sugar, alcohol, dilution, temperature, and batch size all affect whether a frozen drink stays liquid, turns icy, or reaches a smooth texture.</p><a className="section-text-link" href="/learn">Explore every learning guide <span>→</span></a></div><div className="faq-list">{faqs.map(([q, a], index) => <details key={q}><summary><i>{String(index + 1).padStart(2, "0")}</i><b>{q}</b><span>+</span></summary><p>{a}{index === 0 && <a className="faq-learn-link" href="/learn/fix-my-slush">Read the complete troubleshooting guide →</a>}</p></details>)}</div></div></section>

        <DownloadCta id="download" />
      </main>

      <footer><div><Wordmark /><p>Frozen drink recipes and slush math.</p></div><div className="footer-links"><div><b>EXPLORE SLUSHIQ</b><a href="#features">Tools</a><a href="/recipes-and-library">Recipes &amp; My Library</a><a href="/labs">How It Works</a><a href="/learn">Learn</a><a href="#faq">FAQ</a></div><div><b>CONNECT</b><a href="https://www.tiktok.com/@slushiqapp" target="_blank" rel="noreferrer">TikTok</a><a href="https://www.reddit.com/r/slushrecipes/" target="_blank" rel="noreferrer">Reddit community</a><a href="/support">Support</a></div><div><b>LEGAL</b><a href="/privacy">Privacy</a><a href="/terms">Terms</a></div></div><p className="legal">© 2026 SlushIQ. SlushIQ is an independent product and is not affiliated with or endorsed by Ninja, Iceman, VEVOR, or GreenPan. All third-party product names and trademarks belong to their respective owners.</p></footer>
    </>
  );
}
