import type { Metadata } from "next";
import Link from "next/link";
import { ArticleCta, SiteFooter, SiteHeader } from "../../site-chrome";

export const metadata: Metadata = {
  title: "Slush Machine Calculator for Home Frozen Drinks",
  description: "Learn what a slush machine calculator checks and how SlushIQ balances sugar, alcohol, dilution, Brix, and batch size for home machines.",
  alternates: { canonical: "https://slushiq.com/learn/slush-machine-calculator" },
  openGraph: { title: "Slush Machine Calculator for Home Frozen Drinks", description: "Calculate a freeze-ready batch without relying on a universal ratio.", url: "https://slushiq.com/learn/slush-machine-calculator", type: "article" },
};

export default function SlushCalculatorPage() {
  const schema = { "@context": "https://schema.org", "@type": "Article", headline: "How a Slush Machine Calculator Works", description: "A guide to balancing sugar, alcohol, dilution, and batch size for a home slush machine.", author: { "@type": "Organization", name: "SlushIQ" }, publisher: { "@type": "Organization", name: "SlushIQ" }, mainEntityOfPage: "https://slushiq.com/learn/slush-machine-calculator" };
  return <><SiteHeader /><main className="article-page"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><header className="article-hero"><p className="section-kicker">SLUSH MACHINE CALCULATOR</p><h1>Freeze-ready math.<br /><em>Before you pour.</em></h1><p>Home slush machines need a mixture that can form small ice crystals while remaining soft enough to dispense. SlushIQ estimates the balance across sugar, alcohol, water, and total batch volume for compressor-style frozen-drink machines.</p></header><div className="article-body"><article><p className="article-lede">A useful calculator looks at the complete batch—not just one ratio—and translates the result into measurements you can actually use.</p><h2>What the calculator needs to know</h2><section><span>01</span><div><h3>Total batch size</h3><p>The same ingredients behave differently in a 16-ounce test batch and a full machine bowl. Every amount must be evaluated against final volume.</p></div></section><section><span>02</span><div><h3>All sources of sugar</h3><p>Juice, soda, syrup, liqueur, purée, and bottled mixer can all contribute dissolved sugar.</p></div></section><section><span>03</span><div><h3>Alcohol strength and volume</h3><p>The calculator uses the amount and ABV of each alcoholic ingredient to estimate final-batch alcohol.</p></div></section><section><span>04</span><div><h3>Your machine and units</h3><p>Machine capacity and preferred measurements help turn the analysis into a batch that fits the equipment and is practical to pour.</p></div></section><div className="callout"><b>There is no universal slush ratio.</b><p>A fixed mixer-to-water rule cannot account for every juice, spirit, syrup, or machine. Ingredient-level calculation provides more useful guidance.</p></div><h2>SimpleLAB, DesignLAB, or Brixley?</h2><p>Use SimpleLAB for a store-bought mixer, DesignLAB when building ingredient by ingredient, and Brixley when a mixture already in the bowl needs troubleshooting. Successful batches can be saved in My Library for later scaling and reuse.</p><h2>Which home slush machines can SlushIQ help with?</h2><p>SlushIQ is designed for compressor-style home frozen-drink machines from a range of manufacturers. Always follow the capacity, ingredient, safety, and operating instructions supplied with your exact machine.</p><div className="next-reading"><span>KEEP LEARNING</span><Link href="/learn/fix-my-slush">Why won’t my slush freeze? →</Link><Link href="/learn/what-is-brix">What Brix means for frozen drinks →</Link><Link href="/learn/alcohol-and-slush">How alcohol changes the freeze →</Link></div></article><ArticleCta /></div></main><SiteFooter /></>;
}
