import type { Metadata } from "next";
import Link from "next/link";
import { ArticleCta, SiteFooter, SiteHeader } from "../../site-chrome";

export const metadata: Metadata = {
  title: "What Makes a Frozen Drink Recipe Work?",
  description: "Learn how sugar, alcohol, dilution, temperature, and batch size determine whether a frozen drink recipe becomes smooth slush.",
  alternates: { canonical: "https://slushiq.com/learn/frozen-drink-recipes" },
  openGraph: { title: "What Makes a Frozen Drink Recipe Work?", description: "The practical rules behind a smooth frozen drink—and how to adapt your own recipe.", url: "https://slushiq.com/learn/frozen-drink-recipes", type: "article" },
};

export default function FrozenDrinkRecipesPage() {
  const schema = { "@context": "https://schema.org", "@type": "Article", headline: "What Makes a Frozen Drink Recipe Work?", description: "A practical guide to balancing sugar, alcohol, dilution, temperature, and batch size for home frozen-drink machines.", author: { "@type": "Organization", name: "SlushIQ" }, publisher: { "@type": "Organization", name: "SlushIQ" }, mainEntityOfPage: "https://slushiq.com/learn/frozen-drink-recipes" };
  return <><SiteHeader /><main className="article-page"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><header className="article-hero"><p className="section-kicker">FROZEN DRINK RECIPES</p><h1>A good drink recipe<br /><em>isn’t always a good slush recipe.</em></h1><p>A recipe for a home frozen-drink machine needs enough dissolved sugar for a smooth texture, enough water to freeze, and—when alcohol is included—a final strength the machine can handle. The same fundamentals apply across compressor-style home machines.</p></header><div className="article-body"><article><p className="article-lede">The flavor can be perfect while the freeze balance is completely wrong. Here is what a home frozen-drink machine needs from the mixture.</p><h2>Four things successful frozen drink recipes have in common</h2><section><span>01</span><div><h3>The complete sugar load is counted</h3><p>Soda, juice, syrup, purée, liqueur, and prepared mixer can all add sugar. Looking at only one ingredient can hide the true total.</p></div></section><section><span>02</span><div><h3>Alcohol is calculated across the final batch</h3><p>Spirits and liqueurs lower the freezing point. Final-batch ABV matters more than the number of liquor pours.</p></div></section><section><span>03</span><div><h3>The batch fits the machine</h3><p>Scale every ingredient together and stay within the fill and ingredient guidance for your exact machine.</p></div></section><section><span>04</span><div><h3>The mixture starts cold</h3><p>Pre-chilled ingredients help many machines reach serving texture faster and make troubleshooting more reliable.</p></div></section><div className="callout"><b>Want the actual recipe collection?</b><p>SlushIQ keeps its human-created frozen-drink recipes inside the iPhone and Android app, where they can be scaled, saved, and used with the calculation tools.</p></div><h2>Can you convert a regular cocktail or mocktail?</h2><p>Often, yes—but simply pouring the original recipe into the machine may not work. Use DesignLAB to rebuild it ingredient by ingredient, or SimpleLAB when starting from a bottled mixer. SlushIQ checks sugar, alcohol, dilution, and total volume together.</p><h2>What if a frozen drink recipe will not freeze?</h2><p>Record every ingredient and amount before changing the batch. Too much alcohol or sugar can keep it liquid, while too little dissolved sugar may create a hard or icy texture. Brixley can review the full mixture and suggest a measured adjustment.</p><div className="next-reading"><span>KEEP LEARNING</span><Link href="/learn/slush-machine-calculator">How a slush machine calculator works →</Link><Link href="/learn/fix-my-slush">Why won’t my slush freeze? →</Link><Link href="/learn/alcohol-and-slush">How alcohol changes the freeze →</Link></div></article><ArticleCta /></div></main><SiteFooter /></>;
}
