import type { Metadata } from "next";
import Link from "next/link";
import { DownloadCta, SiteFooter, SiteHeader } from "../site-chrome";

export const metadata: Metadata = {
  title: "Frozen Drink Recipes & My Library | SlushIQ",
  description: "Browse human-created frozen drink recipes, save favorites, create custom slush recipes, and scale successful batches in the SlushIQ recipe app.",
  alternates: { canonical: "https://www.slushiq.com/recipes-and-library" },
};

export default function RecipesAndLibraryPage() {
  return <><SiteHeader /><main className="library-page">
    <section className="library-hero">
      <div className="library-hero-copy"><p className="section-kicker">RECIPES + MY LIBRARY</p><h1>Find a favorite.<br /><em>Keep what works.</em></h1><p>Browse human-created frozen drink recipes, save the ones you love, and keep your own successful slush recipes ready to make again. SlushIQ brings discovery and your personal recipe collection into one app.</p><div className="recipe-trust"><span>✓</span><div><b>Designed by people. Not generated by AI.</b><small>SlushIQ recipes are created with home frozen-drink machines in mind.</small></div></div></div>
    </section>

    <section className="library-showcase" aria-label="SlushIQ Recipes and My Library app screens">
      <div className="library-hero-screens"><img src="/app-recipes.png" alt="Browse human-created frozen drink recipes in SlushIQ" /><img src="/app-library.png" alt="Saved recipes and custom recipes in SlushIQ My Library" /></div>
    </section>

    <section className="library-details">
      <article><span>01 / DISCOVER</span><h2>Recipes built<br /><em>for the machine.</em></h2><p>Explore human-created frozen drink recipes for Ninja SLUSHi, Iceman, and other home slushie machines. Browse by style or ingredient, open the batch you want, and scale it for the amount you plan to make.</p><ul><li>Designed by people, not generated by AI</li><li>Alcoholic and non-alcoholic options</li><li>Amounts that scale with the batch</li><li>Favorites kept close at hand</li></ul><Link href="/learn/frozen-drink-recipes" className="text-cta">What makes a frozen drink recipe work? <span>→</span></Link></article>
      <div className="library-detail-screen"><img src="/app-recipes.png" alt="SlushIQ frozen drink recipe collections" /></div>
    </section>

    <section className="library-details library-details-reverse">
      <article><span>02 / SAVE + CREATE</span><h2>Your recipes.<br /><em>Your repeatable wins.</em></h2><p>My Library keeps SlushIQ favorites beside the custom recipes you create in DesignLAB or save after working with Brixley. Reopen a successful batch, scale every ingredient together, and make it again without rebuilding the math.</p></article>
      <div className="library-detail-screen"><img src="/app-library.png" alt="Custom and saved frozen drink recipes in My Library" /></div>
    </section>

    <section className="library-ways"><div><p className="section-kicker">ONE LIBRARY, MORE THAN ONE WAY IN</p><h2>Save the recipe.<br /><em>Remember the result.</em></h2></div><div className="library-way-list"><p><b>Favorite a SlushIQ recipe</b><span>Keep a recipe you enjoy ready for the next batch.</span></p><p><b>Create with DesignLAB</b><span>Build your own recipe and save the final ingredient list.</span></p><p><b>Rescue with Brixley</b><span>Fix the batch, then keep the corrected version for later.</span></p></div></section>

    <DownloadCta />
  </main><SiteFooter /></>;
}
